# 代理服务器配置
[servers]
# 可以添加多个服务器地址
addresses = [
    "47.79.39.75:1080",
     "107.174.218.153:1080", 

    
    
   
]

# DNS 解析配置
[dns]
# 国内 DoH 服务器
china_doh = "https://1.12.12.12/dns-query"
# 国际 DoH 服务器
global_doh = "https://8.8.8.8/dns-query"
# 通用DoH服务器
#doh = "https://rapid-paper-c846.aimerlp19.workers.dev/dns-query"
doh = "https://1.1.1.1/dns-query"
#doh = "http://127.0.0.1:5353/dns-query"
# 备用DoH服务器
adg = "http://94.140.14.14/resolve"
pub_dns = "https://doh.pub/dns-query"

# 功能配置
[features]
# Shadowsocks 密钥（base64 编码）
ss_key = "JtivfX27TuAkUkfgFXGuEQ=="

# 客户端配置
[client]
# TCP监听地址
listen_addr_v4 = "0.0.0.0:1081"
listen_addr_v6 = "[::]:1088"
# UDP监听地址
udp_listen_addr_v4 = "0.0.0.0:1080"
udp_listen_addr_v6 = "[::]:1080"
# GeoIP数据库路径
geoip_db_path = "GeoLite2-Country.mmdb"
# 代理服务器地址
proxy_addr = "127.0.0.1"
# 代理服务器端口
proxy_port = 9090
# 请求超时时间（毫秒）
request_timeout = 5000

# TUN设备配置
[tun]
# 是否启用TUN设备
enabled = true
# TUN设备名称
name = "utun7"
# TUN设备IP地址
address = "172.16.0.1"
# 子网掩码
netmask = "255.255.255.0"
# MTU值
mtu = 1500
# 是否拦截DNS请求
dns_hijack = true
# 需要通过TUN设备路由的网络
routes = [
    "1.1.1.1/32",     # Cloudflare DNS
    "8.8.8.8/32",     # Google DNS
    "223.6.6.6",       # 阿里云  DNS
    "198.18.0.0/16",  # FakeIP范围
    "149.154.160.0/20", #电报ip
    "fc00::1/18"      # IPv6支持
]

# 直连域名列表
[domains]
direct = [
    "baidu.com",
    "qq.com",
    "bilibili.com",
    "bdimg.com",
    "bdstatic.com",
    "hdslb.com",
    "baidubce.com",
    "bcebos.com",
    "bilivideo.com",
    "biliapi.net",
    "bili",
    "zhihu.com",
    "zhimg.com",
    "bilivideo.cn",
    "biliapi.net"
] 
# #proxy
proxy = [
    # 谷歌相关
    "google.com",
    "google-analytics.com",
    "googleapis.com",
    "gstatic.com",
    "doubleclick.net",
    "www.google-analytics.com",
    "www.googleapis.com",
    "www.gstatic.com",
    "www.doubleclick.net",
    "beacons.gcp.gvt2.com",

    #linux.do相关
    "linux.do"

] 